# Generated by Django 5.0 on 2024-02-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0003_alter_task_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='done',
            field=models.CharField(choices=[('C', 'Complete'), ('I', 'Incomplete')], default='I', max_length=1),
        ),
    ]
